services:
  pingspot-redis:
    image: redis:latest
    container_name: pingspot_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - pingspot_redis_data:/data
    networks:
      - pingspot_network

  pingspot-postgres:
    image: postgres:latest
    container_name: pingspot_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRE_DB}
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
    ports:
      - "${POSTGRE_PORT}:5432"
    env_file:
      - .env
    volumes:
      - pingspot_postgre_data:/var/lib/postgresql/data
    networks:
      - pingspot_network

networks:
  pingspot_network:

volumes:
  pingspot_redis_data:
  pingspot_postgre_data: